import React, { Component } from "react";
import { Line } from "react-chartjs-2";

var activityData = [
   {
      first: [
         20,
         30,
         25,
         28,
         23,
         32,
         26,
         32,
         21,
         35,
         24,
         28,
         22,
         27,
         30,
         35,
         20,
         25,
         22,
         29,
      ],
      second: [
         35,
         40,
         30,
         38,
         32,
         42,
         30,
         35,
         40,
         30,
         45,
         30,
         35,
         40,
         30,
         38,
         32,
         42,
         32,
         42,
      ],
   },
   {
      first: [
         35,
         35,
         40,
         30,
         38,
         40,
         30,
         38,
         32,
         42,
         32,
         42,
         32,
         42,
         30,
         35,
         22,
         30,
         45,
         30,
      ],
      second: [
         35,
         40,
         40,
         30,
         38,
         32,
         42,
         32,
         42,
         30,
         38,
         32,
         42,
         30,
         35,
         22,
         30,
         45,
         30,
         35,
      ],
   },
   {
      first: [
         35,
         40,
         40,
         30,
         38,
         32,
         42,
         32,
         42,
         30,
         38,
         32,
         42,
         30,
         35,
         22,
         30,
         45,
         30,
         35,
      ],
      second: [
         30,
         35,
         40,
         30,
         38,
         32,
         42,
         32,
         42,
         35,
         40,
         30,
         38,
         32,
         42,
         30,
         35,
         22,
         30,
         45,
      ],
   },
   {
      first: [
         35,
         40,
         30,
         38,
         32,
         42,
         30,
         35,
         22,
         30,
         45,
         30,
         35,
         40,
         30,
         38,
         32,
         42,
         32,
         42,
      ],
      second: [
         35,
         35,
         40,
         30,
         38,
         40,
         30,
         38,
         32,
         42,
         32,
         42,
         32,
         42,
         30,
         35,
         22,
         30,
         45,
         30,
      ],
   },
];

class LineChart7 extends Component {
   render() {
      const data = {
         labels: [
            "01",
            "02",
            "03",
            "04",
            "05",
            "06",
            "07",
            "08",
            "09",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
            "18",
            "19",
            "20",
         ],
         datasets: [
            {
               label: "Active",
               backgroundColor: "rgba(82, 177, 65, 1)",
               borderColor: "rgba(82, 177, 65, 1)",
               data: activityData[this.props.data ? this.props.data : 0].first,
               borderWidth: "none",
            },
            {
               label: "Inactive",
               backgroundColor: "rgba(255, 142, 38, 1)",
               borderColor: "rgba(255, 142, 38, 1)",
               data: activityData[this.props.data ? this.props.data : 0].second,
               borderWidth: "none",
            },
         ],
      };

      const options = {
         responsive: true,
         maintainAspectRatio: false,
         elements: {
            point: {
               radius: 0,
            },
         },
         legend: false,

         scales: {
            yAxes: [
               {
                  gridLines: {
                     color: "rgba(89, 59, 219,0.1)",
                     drawBorder: true,
                  },
                  ticks: {
                     fontColor: "#999",
                  },
               },
            ],
            xAxes: [
               {
                  gridLines: {
                     display: false,
                     zeroLineColor: "transparent",
                  },
                  ticks: {
                     stepSize: 5,
                     fontColor: "#999",
                     fontFamily: "Nunito, sans-serif",
                  },
               },
            ],
         },
         tooltips: {
            enabled: false,
            mode: "index",
            intersect: false,
            titleFontColor: "#888",
            bodyFontColor: "#555",
            titleFontSize: 12,
            bodyFontSize: 15,
            backgroundColor: "rgba(256,256,256,0.95)",
            displayColors: true,
            xPadding: 10,
            yPadding: 7,
            borderColor: "rgba(220, 220, 220, 0.9)",
            borderWidth: 2,
            caretSize: 6,
            caretPadding: 10,
         },
      };

      return <Line data={data} options={options} height={300} />;
   }
}

export default LineChart7;
